### PR TITLE
Portuguese European pt-PT translatio complete

### PR DESCRIPTION
**Pull request by Ricardo-Simoes**
Portuguese European (**pt-PT)** is different from Portuguese Brazilian (**pt-BR**). I noticed that only pt-BR existed, so I did a pt-PT translation.
**NOTE:** As is stands, (before this commit, see attached pic), the Portuguese flag is (wrongly) corresponding to the only existing until now Portuguese BR, so if you agree to add my pt-PT translation, you should change it to the Brazilian flag...
In the end the correct standard is: **Portuguese** pt-PT (Portuguese flag) ; **Portuguese Brazilian** pt-BR (Brazilian flag).
Best regards
Ricardo Simões
xmcorporation.com
Captura de ecrã_2022-08-08_17-31-21

### CODE REVIEW

**Comment by Shatur** [comment]
Thank you!

**Comment by Shatur** [comment]
> NOTE: As is stands, (before this commit, see attached pic), the Portuguese flag is (wrongly) corresponding to the only existing until now Portuguese BR, so if you agree to add my pt-PT translation, you should change it to the Brazilian flag...
In the end the correct standard is: Portuguese pt-PT (Portuguese flag) ; Portuguese Brazilian pt-BR (Brazilian flag).

In your image you show translation languages where the flag of Portugal is used for Portuguese. Is it wrong? Here is the code:
https://github.com/crow-translate/crow-translate/blob/f12f68a2fd61a930063271bcb4b9697e28d7e799/src/languagebuttonswidget.cpp#L310-L311

In the settings we use Brazil flag for pt-BR.

**Comment by Shatur** [comment]
Here is how it looks after your PR and 2e1334f5b3021c169313ebd10ce01155a69c4b18:
изображение

**Comment by Shatur** [comment]
BTW, you have some untranslated strings: https://crowdin.com/project/crow-translate/pt-PT
Feel free to finish the translation in the web version.

**Comment by Ricardo-Simoes** [comment]
> BTW, you have some untranslated strings: https://crowdin.com/project/crow-translate/pt-PT Feel free to finish the translation in the web version.

That's strange... I used QT Linguist and it was all green checks... anyway I did has you told and used the web version do translate those 38 strings

**Comment by Ricardo-Simoes** [comment]
> Here is how it looks after your PR and [2e1334f](https://github.com/crow-translate/crow-translate/commit/2e1334f5b3021c169313ebd10ce01155a69c4b18): изображение

Flags are ok, but description is not according to standards... maybe I induced you in error...
The correct is like this:
🇧🇷 Portuguese Brazilian
🇵🇹 Portuguese
or in "Português"
🇧🇷 Português do Brasil
🇵🇹 Português

**Comment by Shatur** [comment]
> but description is not according to standards...

Unfortunately, I can't control it :(
I add it here:
https://github.com/crow-translate/crow-translate/blob/2e1334f5b3021c169313ebd10ce01155a69c4b18/src/settings/settingsdialog.cpp#L89
Which uses [QLocale::nativeLanguageName](https://doc.qt.io/qt-5/qlocale.html#nativeLanguageName):
https://github.com/crow-translate/crow-translate/blob/2e1334f5b3021c169313ebd10ce01155a69c4b18/src/settings/settingsdialog.cpp#L559-L564

**Comment by Ricardo-Simoes** [comment]
> 
> Unfortunately, I can't control it :( I add it here:
> 
No worries then

**Pull request merged**
