### PR TITLE
Switch back to git submodules and pack source release

### PR DESCRIPTION
**Pull request by gasinvein**
Reverts commit eabf0482321097b6d6deeccc44170e431acd4931
Add circle-flags and fluent-icon-theme submodules not present in the original git source tree with submodules.
Set submodule tags to match external project tags set as of commit b0ed075747eea719298ab3cb6581a460030c3ccc

Add GH action for packing full source tarball and adding it to release assets (addresses #116).

### CODE REVIEW

**Comment by Shatur** [comment]
Thank you a lot!
I will wait for CI to complete on your fork (to test the release), merge it and draft a new release here.

**Comment by Shatur** [comment]
It failed: https://github.com/gasinvein/crow-translate/runs/6373190394

**Comment by gasinvein** [comment]
> It failed: https://github.com/gasinvein/crow-translate/runs/6373190394

Yeah, uploading release assets on my fork seems to fail for some seemingly unrelated reason (probably GH server-side issue).

**Comment by Shatur** [comment]
I think you need to set `GITHUB_TOKEN` for your fork. Could you do it to test the source packaging properly?

**Comment by gasinvein** [comment]
> I think you need to set `GITHUB_TOKEN` for your fork. Could you do it to test the source packaging properly?

`GITHUB_TOKEN` should be always set. Or do you mean adding a PAT to secrets?

**Comment by Shatur** [comment]
> GITHUB_TOKEN should be always set.

Oh, you are right. Let's just wait then. Feel free to ping me.

**Comment by gasinvein** [comment]
It appears the issue was missing permission: adding
```yaml
permissions:
  contents: write
```
fixed the release asset upload.

I suspect the already existing actions (for binary packages) will fail for the same reason. Should I add this permission to all asset upload actions?

**Comment by Shatur** [comment]
> Should I add this permission to all asset upload actions?

Yes, please, just to check if resulting binaries are alright too.

**Comment by gasinvein** [comment]
Other assets (binary packages) seem to be uploaded successfully as well, see [here](https://github.com/gasinvein/crow-translate/releases/tag/2.9.2-1).

**Comment by Shatur** [comment]
> It appears the issue was missing permission: adding

Oh, I think this probably non necessary if I already set GitHub actions to read/write in settings? It just worked before.

**Comment by gasinvein** [comment]
Duh, I've forgot about that setting. Indeed, probably not needed if "Read and write permissions" option is set. Should I drop the latest commit, then?

**Comment by Shatur** [comment]
Yes, please :)

**Comment by gasinvein** [comment]
Done. Seems to be working in my fork without job permissions.

**Review by Shatur — APPROVED** [review]

**Comment by Shatur** [comment]
I noticed one inconvenience here. We copying files using CMake into source directory with out third-parties:

https://github.com/crow-translate/crow-translate/blob/bd0c73aaf698d366a06f97d1db4350f9b76e587b/CMakeLists.txt#L130-L131

Since all files located in our source directory I think we should move to `data/third-party` all qrc files and fix names. Mind sending another PR? After this I will draft a new release.

**Comment by gasinvein** [comment]
I'm not really familiar with Qt. Do you mean e.g. in `flags.qrc` changing `<file>us.svg</file>` to something like `<file alias="us.svg">../third-party/circle-flags/flags/us.svg</file>`?

**Comment by Shatur** [comment]
> Do you mean e.g. in flags.qrc changing <file>us.svg</file> to something like <file alias="us.svg">../third-party/circle-flags/flags/us.svg</file>

Yep! But I think it should be without `...`, just `third-party/circle-flags/flags/us.svg`. And you will need to set alias to `ui.svg`. So something like this should work:

```xml
<file alias="us.svg">third-party/circle-flags/flags/us.svg</file>
```

> I'm not really familiar with Qt.

Or you can wait, I will able to fix it myself, but later.

**Comment by gasinvein** [comment]
> I think it should be without `...`, just `third-party/circle-flags/flags/us.svg`.

Then `flags.qrc` should be placed at `data/flags.qrc`?

**Comment by Shatur** [comment]
Oh, yes, we should move `data/third-party` to `data/icons/third-party`.
And we probably could move `flags.qrc` to `data/icons/third-party` to make paths even shorter: `circle-flags/flags/us.svg`?

**Comment by gasinvein** [comment]
Opened #417

**Comment by Shatur** [comment]
I found an issue with this approach. It breaks all symlinks inside tarball. Is there anything we could do about it?

**Comment by gasinvein** [comment]
Probably my `git | tar` command was not as robust as I thought. What symlinks, exactly?

**Comment by Shatur** [comment]
Everything in `data/icons/third-party/fluent-icon-theme/links/`

**Comment by gasinvein** [comment]
Ah, right. Indeed, seems like they're broken by the `--transform=` option for `tar`, I should've added `S` flag (it tells `tar` not to apply path transformation to symlinks).
```patch
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -16,7 +16,7 @@ jobs:
         run: |
           SOURCE_NAME=$(awk -F/ '{print $NF}' <<<"${{ github.repository }}")-$(awk -F/ '{print $NF}' <<<"${{ github.ref }}")
           git ls-files --recurse-submodules | \
-          tar --exclude-vcs --transform "s|^|$SOURCE_NAME/|" -ca -T - -f ../$SOURCE_NAME.tar.gz
+          tar --exclude-vcs --transform "s|^|$SOURCE_NAME/|S" -ca -T - -f ../$SOURCE_NAME.tar.gz
 
       - name: Upload source tarball
         uses: AButler/upload-release-assets@v2.0
```

**Comment by Shatur** [comment]
CI on Windows failed. Probably we should silence warnings on third-paries...

**Comment by Shatur** [comment]
Tried 183a32b8b74a94159b2ca4b140912cf509c0c15d

**Comment by Shatur** [comment]
No, still have warnings from MSVC. The most annoying that this warnings from third-parties.
Now I remember why I moved from submodules. Sorry, reverted temporary until we have a better solution. Currently don't have a time to take a look.

**Comment by gasinvein** [comment]
Looks like I've committed the wrong qtaskbarcontrol tag. Was `2.0.2` in `ExternalLibraries.cmake`, became `2.0.1` in submodule.

**Comment by Shatur** [comment]
Hm... Could you try to revert d8982c0ae9b05de94a138040fd40a47cb0c903b4, apply your fixes on top (including `S`) and open a PR?

**Pull request merged**
