### PR TITLE
add crow-translate_az_AZ

### PR DESCRIPTION
**Pull request by kheyyam**

### CODE REVIEW

**Comment by Shatur** [comment]
You renamed the original `data/translations/crow-translate.ts`, but you need to copy this file. Could you restore the original file at `data/translations/crow-translate.ts`?

**Comment by Shatur** [comment]
There are still conflicts. Could you resolve it?

**Comment by Shatur** [comment]
For unknown reasons GitHub says that `crow-translate.ts`, that's odd. But I noticed that you pushed the translation to Crowdin too. Can I just pull your translation from the Crowdin page instead?

**Comment by kheyyam** [comment]
>  Can I just pull your translation from the Crowdin page instead?

Of course! You can do it.

**Comment by Shatur** [comment]
Merged it #352, thanks!

**Pull request closed without merging**
