### PR TITLE
autoselect source text when showing main window

### PR DESCRIPTION
**Pull request by veksha**
resolves https://github.com/crow-translate/crow-translate/issues/528

### CODE REVIEW

**Comment by Shatur** [comment]
Could you please include changes you did in `vcpkg.json`? Because without it CI won't pass on Windows.
It's a sad that MS saved on storage and don't host sources on their own.

**Comment by veksha** [comment]
> Could you please include changes you did in `vcpkg.json`? Because without it CI won't pass on Windows. It's a sad that MS saved on storage and don't host sources on their own.

to both PR's or as separate PR?

**Comment by Shatur** [comment]
> to both PR's or as separate PR?

Let's do it here, I will rebase on merge.

**Comment by veksha** [comment]
ok. check, please

**Comment by Shatur** [comment]
LGTM, thanks!

**Comment by veksha** [comment]
not sure i did `git submodule update --remote src/qonlinetranslator`
so changes for qonlinetranslator may be still old.

**Comment by Shatur** [comment]
>  so changes for qonlinetranslator may be still old.

It's fine, I will update the submodule myself in a separate commit.

**Pull request merged**
