### PR TITLE
Added Spanish README translation

### PR DESCRIPTION
**Pull request by victorhck**
don't know if can be useful...
You are free to use it or not... :wink:

### CODE REVIEW

**Comment by Shatur95** [comment]
Thanks for the contribution! But I suggest to apply only typos fixes and keep Readme in English because it is hard to maintain it for several languages. But I suggest to translate website instead. Take a look at [this](https://github.com/crow-translate/hugo-website). It already translated to Russian. All you need is update [languages.toml](https://github.com/crow-translate/hugo-website/blob/master/config/_default/languages.toml), then copy `content/en` folder to `content/es` and translate in to Spanish.

**Comment by victorhck** [comment]
Ok! no problem!
Closed

**Comment by Shatur95** [comment]
Could you keep typo fixes in Readme in this PR? :)

**Comment by Shatur95** [comment]
I done it myself.

**Pull request merged**
