### PR TITLE
Add simplified chinese (zh_CN) localization

### PR DESCRIPTION
**Pull request by BruceZhang1993**
add zh (Simplified Chinese) translation

Signed-off-by: Bruce Zhang <zttt183525594@gmail.com>

### CODE REVIEW

**Comment by Shatur95** [comment]
Thank you!

**Comment by Shatur95** [comment]
Note that Transefix says that [some strings](https://www.transifex.com/crow-translate/crow-translate/viewstrings/#zh_CN/crowts/158635838?q=translated%3Ano) are not translated.

**Comment by Shatur95** [comment]
Note that Transefix says that [some strings](https://www.transifex.com/crow-translate/crow-translate/viewstrings/#zh_CN/crowts/158635803?q=translated%3Ano) are not translated.

**Comment by BruceZhang1993** [comment]
@Shatur95 missing some strings by mistake, i can check it on Transfix.

**Pull request merged**
