### PR TITLE
Save audio and text to files

### PR DESCRIPTION
**Pull request by batistasilva**
Some features I've added in my version that I think will be important for one type of person.
Added features to write a text file, which will be translated, as well as write the same to the translated text.
Save tts stream in a file with .mp3 extension. Sequential file if necessary. It will depend on the size of the stream for the read content.
Lets you define a new location to save files in the general menu. It also lets you define a custom name for the file.
Everything has been tested on linux 12 bookworm. I have no way to test on mac or windows system.

### CODE REVIEW

**Comment by batistasilva** [comment]
Yes I Can..
Could you explain to me the best way to send it?
Like screenshot, with the updates or screenshot of where they were made?
can i send it by email?

**Comment by Shatur** [comment]
>  Could you explain to me the best way to send it?

Start with the simplest feature and submit it first.

>  can i send it by email?

Please, use GitHub.

**Comment by Shatur** [comment]
I looked at the code more closely and it looks like it's more of a single feature for saving audio and text. Sorry for inconvenience, I judged by the title too quickly.

I have a few suggestions.
Could you please move these buttons to context menu (that shows up by right clicking on the text)? Because I use this app on my phone and these amount of buttons won't fit the screen.
And could you show [QFileDialog](https://doc.qt.io/qt-5/qfiledialog.html) instead of saving files automatically to the specified folder?

**Comment by batistasilva** [comment]
Got it...
So that part of configuring a workspace, and also defining file names that I put in the general menu, would it no longer be necessary? Which I had been using, right?

**Comment by Shatur** [comment]
> So that part of configuring a workspace, and also defining file names that I put in the general menu, would it no longer be necessary?

Yes, I think it would be more convenient to set names in save dialog after clicking on menu item.

**Comment by Shatur** [comment]
>  I'll discard these changes to the menu then..

Great, thanks!

**Comment by batistasilva** [comment]
> I looked at the code more closely and it looks like it's more of a single feature for saving audio and text. Sorry for inconvenience, I judged by the title too quickly.
> 
> I have a few suggestions. Could you please move these buttons to context menu (that shows up by right clicking on the text)? Because I use this app on my phone and these amount of buttons won't fit the screen. And could you show [QFileDialog](https://doc.qt.io/qt-5/qfiledialog.html) instead of saving files automatically to the specified folder?

Hello, I have a problem, because in the "contextmenu.cpp", I have the data to save the text file. This part is okay. 
But I don't know a way to get the necessary data,  like: ui->translationEdit->translation(), ui->translationEdit->translationLanguage(), currentEngine() from "contextmenu.cpp".
This data I have acess throught "mainwindow.cpp"
What do you think about this?

**Comment by Shatur** [comment]
We pass the edit to our context menu, so you can obtain it from the pointer by simply checking the type:
https://github.com/crow-translate/crow-translate/blob/87aa163f252ecde1d61d9d378bfcbb6d08b176e0/src/contextmenu.h#L42-L45

**Comment by batistasilva** [comment]
> We pass the edit to our context menu, so you can obtain any information from the pointer by simply checking the type:
> 
> https://github.com/crow-translate/crow-translate/blob/87aa163f252ecde1d61d9d378bfcbb6d08b176e0/src/contextmenu.h#L42-L45
> 
> You can also pass more pointers to it if needed.

Okay, I will see how this work...

**Comment by omega3** [comment]
Can we expect to have option to save audio anytime soon? I read Releases and it doesn't mention anything about audio.

@batistasilva As a user of this great program I thank you very much for your commitment. I really missed save audio feature and here it is.

**Comment by batistasilva** [comment]
> Can we expect to have option to save audio anytime soon? I read Releases and it doesn't mention anything about audio.
> 
> @batistasilva As a user of this great program I thank you very much for your commitment. I really missed save audio feature and here it is.

I have it working on my computer version. However, in the github version it is not possible. Because I offered my upgrade and would have to add two buttons to the main menu. So they asked me to put them in the context menu. However, the context menu does not allow access to the data necessary to record the audio file, only a text file which would be the other functionality I have.

My version is like this: 
image

**Comment by Shatur** [comment]
> However, the context menu does not allow access to the data necessary to record the audio file

You have access to text from it. If you need to pass more data - feel free to do so. It should be in context menu because it's too much buttons, it simply won't fit in mobile version.

**Comment by omega3** [comment]
I like it the way Batista shows. I assume that users on mobile won't use these buttons, at least it will be less common. I use this program on desktop. Would it be possible to add options in settings to show / hide these buttons? Users on desktop will use it more frequently, so buttons as shown on screenshot next to already existing buttons is a good solution. Adding them in context menu is less convenient for desktop users.
Maybe changing text "translate automatically" into icon would free some space.

**Comment by Shatur** [comment]
I would prefer to have a context menu that is accessible easily on desktop instead of a settings that hides buttons and defaults to "hidden" on mobile.

**Pull request closed without merging**
