### PR TITLE
Fix translations installation dir

### PR DESCRIPTION
**Pull request by tim77**
`APPLICATION_ID` is common place for translation files. This also fixes RPM macros for finding languages automatically. Space symbol breaks `%find_lang <foo> --with-qt` macros.

This could help with packaging Crow Translate for official Fedora repo.

https://docs.fedoraproject.org/en-US/packaging-guidelines/#handling_locale_files

### CODE REVIEW

**Comment by Shatur** [comment]
Thank you!

**Comment by Shatur** [comment]
I will draft a new release later today.

**Comment by tim77** [comment]
Please hold a little bit and i think i could missed something related to translations location. I will test it more.

**Comment by Shatur** [comment]
Okay!

**Comment by Shatur** [comment]
Oh, yes, you probably need to update the pass in the `appsettings.cpp`.

**Pull request merged**
