### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by Shatur95** [comment]
Thank you! But could you send it to [Crowdin](https://crowdin.com/project/crow-translate) page instead? I just added Dutch language.

**Comment by Vistaus** [comment]
I don't like Crowdin, but I just added it.

**Comment by Shatur95** [comment]
> Btw, if you want people to use Crowdin, you might want to remove the "Send me a pull request part" from the translation section of Readme.md wink

Yes, just recently noticed that Crowdin produces a bit different localization files (you can check it in #222), but forgot to update the `README.md`. So, now I suggesting to use Crowdin instead to reduce diffs.
Sorry if I confuse you.

**Comment by Shatur95** [comment]
Merged by #222, thank you!

**Comment by Shatur95** [comment]
> Yes, just recently noticed that Crowdin produces a bit different localization files

Also support promised to fix the problem :)
Hope it will be soon since I understand that it is more convenient for many to use Qt Linguist.

**Comment by Vistaus** [comment]
> Hope it will be soon since I understand that it is more convenient for many to use Qt Linguist.

Yeah! That would be great! 🙂

**Pull request closed without merging**
