### PR TITLE
Update Spanish translation

### PR DESCRIPTION
**Pull request by victorhck**

### CODE REVIEW

**Comment by Shatur95** [comment]
Thank you!

**Comment by victorhck** [comment]
a pleasure!
feel free to ping me if there's new translations to do with new releases or such! ;)
BTW, I have an issue.

**Comment by Shatur95** [comment]
>  feel free to ping me if there's new translations to do with new releases or such! ;)

Just pushed new strings. I would suggest you use [Crowdin](https://crowdin.com/project/crow-translate), you will always be notified when a translation needs to be updated.

**Comment by victorhck** [comment]
Weblate, Transifex, Crowdin... so many platforms and accounts in many places... :)

**Pull request merged**
