### PR TITLE
Prevent compilation with Fix Clang Tidy warnings

### PR DESCRIPTION
**Pull request by Shatur95**

### CODE REVIEW

**Comment by toprak** [comment]
Yo mate! Give us the new relase I am looking forward for it!

**Comment by Shatur95** [comment]
:D I am currently testing.

But you can try it yourself right now very easily:

```
git clone git@github.com:crow-translate/crow-translate.git
cd crow-translate
mkdir build
cd build
cmake -D CPACK_GENERATOR="DEB" -D CMAKE_BUILD_TYPE=Release ..
cmake --build . --target package
```

And you will have deb package.

**Comment by toprak** [comment]
I am on windows dude

**Comment by Shatur95** [comment]
Well, no easily...
Last 2 steps will be:

```bash
cmake -D CPACK_GENERATOR="NSIS" -D VCPKG_TARGET_TRIPLET=x64-windows -D CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ..
cmake --build . --target package --config Release
```

And you will have the installer. But you need compiler with Qt5 and Tesseract libraries for it. So, you probably need to wait a bit. I will try to setup CI ASAP. After adding Tesseract I need to update [release](https://github.com/crow-translate/crow-translate/blob/master/.github/workflows/release.yml) configuration, that's why I experimenting with this.

If you still want to try it on Windows, I can help you setup things. Basically, you need MSVC and [vcpkg](https://github.com/microsoft/vcpkg) to get dependencies.

**Comment by toprak** [comment]
No no, you already have tons of work, I can wait. Thanks mate.

**Comment by Shatur95** [comment]
Sorry for a such long delay. I finaly figured out how to easily bundle all necessary Dlls for Windows. I used windeploy before because I had only Qt dependencies. But now I automated this process with `vcpkg` to bundle Tesseract and it dependencies.

I will draft a new release tomorrow morning. Thank you for your patience.

**Comment by toprak** [comment]
@Shatur95 This is really great new! Thank you, finally I can use manga and comics to learn language.

**Comment by Shatur95** [comment]
Sorry, there is some small issues with CMake modules that I wrote. I will fix it right after the job. So, release binaries will be available in the evening.

**Comment by toprak** [comment]
Mate did you forget to add windows version?

**Comment by Shatur95** [comment]
No, the Windows version is currently [being built in CI](https://github.com/crow-translate/crow-translate/runs/1289140931?check_suite_focus=true) :(
Since there is no cache, it will be available for about two hours. Next builds will be done in about 5 minutes.

**Pull request merged**
